### ISSUE TITLE
Placing the Java API in a Maven repository

### ISSUE THREAD

**Issue by ratliff** [kaltura/server#1068]
It would be enormously helpful to me, and presumably other Java developers, if you would place the Java API in a Maven repository.  I have written some Kaltura code that I have placed in GitHub.  I would like to use Maven to manage the build process and NOT require that the Java API be downloaded and compiled separately.

Let me know if the API already exists in a repository that I am not aware of.

Thanks

**Comment by jessp01** [comment]
Hi @ratliff,

We've actually made some progress from an infra standpoint since this was last discussed.
We now have this script which compiles the clientlibs and then runs the unittests:
https://github.com/kaltura/server/blob/Jupiter-10.8.0/generator/sources/java/testAPI/test.sh
And also a build file for ant:
https://github.com/kaltura/server/blob/Jupiter-10.8.0/generator/sources/java/build.xml

There is an automation generating clientlibs daily and pushing it onto the KalturaGeneratedAPIClients.* repos and a Travis hook on these repos to build and run the units [it calls testAPI/test.sh in the case of the Java client.

You can see the Travis runs here:
https://travis-ci.org/kaltura/KalturaGeneratedAPIClientsJava

We would be happy to use Maven for compiling and pushing it onto a Maven repo, hosted at the gh_pages of https://github.com/kaltura/KalturaGeneratedAPIClientsJava, similarly to what is described here:
http://blog.kaltepoth.de/posts/2010/09/06/github-maven-repositories.html

Would you be interested in creating a pom.xml to support this and making a pull request?
Thanks,

**Comment by ratliff** [comment]
Sure, I can have a go at it.  May take me a few days.

**Comment by ratliff** [comment]
Neither your bash script nor your build.xml file will work for me.  And some of the problems are fairly obvious (incorrect pathnames, etc).

Which branch of your repository should I be looking at?  Jupiter-10.8.0 ???

Can we have a Skype call tomorrow morning to discuss?

**Comment by jessp01** [comment]
Closing as this discussion resulted in this pull request:
https://github.com/kaltura/server/pull/2397

Mark, thank you, I am testing the code generation from your clone now.
