### ISSUE TITLE
KMC studio v1.9.4 not displaying after install

### ISSUE THREAD

**Issue by milentheman** [kaltura/server#2234]
Hi,

issue with my Kaltura KMC Studio it really never displayed and I checked and could not see the reason why .

********* kaltlog shows this when clicking on the studio

==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Wed Feb 11 13:52:34 2015] [error] [client 192.168.100.199] File does not exist: /opt/kaltura/app/alpha/web/apps/studio, referer: http://media.mimodata.com/index.php/kmc/kmc4

********* running  /opt/kaltura/bin/kaltura-sanity.sh    shows these failing the sanity check 
 
[check_studio_index_page] [FAILED, RC: 1] - [.609633211]
[DWH cycle] [FAILED, RC: 255] - [23.830167963]
[Red5 file upload] [FAILED, RC: 2] - [.745232135]

********* and on the webpage i can only see this message:

"Not Found

The requested URL /apps/studio/v1.9.4/index.html was not found on this server.

Apache/2.2.15 (CentOS) Server at media.mimodata.com Port 80"

**Comment by AquileaSFX** [comment]
Hello,

did you install using rpm?
if thats the case please do 
yum install kaltura-html5-studio

**Comment by milentheman** [comment]
Hi used the single server installation from the forum but nevertheless tried still no joy as it is already installed

[root@media ~]# yum install kaltura-html5-studio
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.serverspace.co.uk
 * extras: centos.serverspace.co.uk
 * updates: centos.serverspace.co.uk
Kaltura                                                  | 2.9 kB     00:00
Kaltura-noarch                                           | 2.9 kB     00:00
base                                                     | 3.7 kB     00:00
extras                                                   | 3.4 kB     00:00
updates                                                  | 3.4 kB     00:00
Package kaltura-html5-studio-v1.9.4-1.noarch already installed and latest version
Nothing to do
[root@media ~]#

**Comment by jessp01** [comment]
Hello,

Please post on forum.kaltura.org instead since this is not a general issue [studio works well for me in this version].
Also, for bug reporting please refer to:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.5.0/doc/Contributing-to-the-Kaltura-Platform.md#which-repositories-should-i-contribute-to

As far as your issue, here are some things to check:
0. \# rpm -ql kaltura-html5-studio
Lets see what the package is reported to contain, output should be:
/opt/kaltura/apps/studio/v1.9.4
/opt/kaltura/apps/studio/v1.9.4/css
/opt/kaltura/apps/studio/v1.9.4/css/fonts
/opt/kaltura/apps/studio/v1.9.4/css/fonts/icomoon1.eot
/opt/kaltura/apps/studio/v1.9.4/css/fonts/icomoon1.svg
/opt/kaltura/apps/studio/v1.9.4/css/fonts/icomoon1.ttf
/opt/kaltura/apps/studio/v1.9.4/css/fonts/icomoon1.woff
/opt/kaltura/apps/studio/v1.9.4/css/select2-spinner.gif
/opt/kaltura/apps/studio/v1.9.4/css/select2.png
/opt/kaltura/apps/studio/v1.9.4/css/select2x2.png
/opt/kaltura/apps/studio/v1.9.4/css/studio.css
/opt/kaltura/apps/studio/v1.9.4/css/vendor.css

And many other files.

Check that these files exist on disk, if not, try:
\# yum reinstall kaltura-html5-studio

If it still does not work, post on the forum.
Thanks,
