### ISSUE TITLE
access control / authorized countries

### ISSUE THREAD

**Issue by himbeere** [kaltura/server#2300]
Hola.

How is this feature "access control / authorized countries" supposed to work? I tried many times to restrict access to videos for example to germany but as soon as i try to whatch a video i get the "this video is only available in certain countries" message. So it doesn't do what i expect it to do.

cheers 
t.

**Comment by erankor** [comment]
The reason is probably because Kaltura CE ships with a very old ip2location database. We're quite limited in what we can offer in the free open source version (the old database that is bundled with the code is from the times it was free...)
If you need this functionality, you can purchase a more up-to-date database from ip2location.com, optionally with periodic updates.

**Comment by jessp01** [comment]
Please note that CE is not bundled directly with IP2Location due to their license restrictions. you can download the free ver on their site but note it will only provide some of the functionality. As Eran said, you can also buy the commercial ver to get all data they can offer.
