### ISSUE TITLE
server/alpha/lib/model/DeliveryProfileDynamicAttributes::filterFlavorsByTags returned too early ignore second argument in the array

### ISSUE THREAD

**Issue by omridevk** [kaltura/server#2670]
public function filterFlavorsByTags($flavors)
	{
		foreach ($this->tags as $tagsFallback)
		{
			$curFlavors = array();
				
			foreach ($flavors as $flavor)
			{
				foreach ($tagsFallback as $tagOption)
				{
					if (!$flavor->hasTag($tagOption))
						continue;
					$curFlavors[] = $flavor;
					break;
				}
			}
				
			if ($curFlavors)
				return $curFlavors;
		}
		return array();
	}

It seems that we return curFlavors, then resetting it before having a chance to go through the second tag argument.

if ($curFlavors)
return $curFlavors;

This seems to solve it:

	public function filterFlavorsByTags($flavors)
	{
        $curFlavors = array();
		foreach ($this->tags as $tagsFallback)
		{

			foreach ($flavors as $flavor)
			{
				foreach ($tagsFallback as $tagOption)
				{
					if (!$flavor->hasTag($tagOption))
						continue;
					$curFlavors[] = $flavor;
					break;
				}
			}
            
		}
            return $curFlavors;
	}

The above is seen when performing the following:

{serviceUrl}/p/{partnerId}/sp/{partnerId}00/playManifest/entryId/{entryId}/tags/{tags}/format/applehttp/protocol/http/a.m3u8

**Comment by erankor** [comment]
this behavior is by design, the tags are grouped into one or more fallback options, within each group the relation between tags is OR. so - array(array('a', 'b'), array('c', 'd')) means - try to find any flavors that have either a or b, if you found any, use those flavors. otherwise, try to find any flavors that have either c or d. the reason is that not all flavors can play together in a single adaptive set. for example, the array i provided above means - a & b can play together, and c & d can play together, but these two groups should not be mixed
