### ISSUE TITLE
HDS play back gives a "no media found" ( 10.19.0 CE on CentOS Linux release 7.1.1503 )

### ISSUE THREAD

**Issue by GeraldNathan** [kaltura/server#3292]
HDS playback works in centOS 6 ( 10.16) with similar setting but not in 7 ( 10.19)

Video link:

http://kac.corpus.com/index.php/extwidget/preview/partner_id/101/uiconf_id/23448134/entry_id/0_8snosjuo/embed/dynamic?&flashvars[akamaiHD]=%7B%22loadingPolicy%22%3A%22preInitialize%22%2C%22asyncInit%22%3A%22true%22%7D&flashvars[twoPhaseManifest]=true&flashvars[streamerType]=hdnetworkmanifest

Client machine is unable to get the hds manifest file:

Tried the following:
1. tried to curl from the local machine file is not found.(from nginx)

http://kac.corpus.com:88/hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_,o0e4sjzi,t9lila38,uz8zj8o2,shkeltsk,5f3m40l2,/forceproxy/true/name/a.mp4.urlset/manifest.f4m?g=TMPFMHFHBYDG&hdcore=3.1.0&plugin=aasp-3.1.0.43.124

Port 88 is open and is available.

[root@kac nginx]# grep ip_range /opt/kaltura/app/configurations/local.ini
internal_ip_range = 207.97.147.202

nginx error log:
2015/10/08 18:44:54 [error] 44364#44364: *33 ngx_http_vod_process_header: content length 1926064 exceeds the limit 1090 while reading response header from upstream, client: 207.97.147.202, server: kac.corpus.com, request: "GET /hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_,o0e4sjzi,t9lila38,uz8zj8o2,shkeltsk,5f3m40l2,/forceproxy/true/name/a.mp4.urlset/manifest.f4m?g=TMPFMHFHBYDG&hdcore=3.1.0&plugin=aasp-3.1.0.43.124 HTTP/1.1", subrequest: "/child_request//hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_o0e4sjzi/forceproxy/true/name/a.mp4", upstream: "kalapi://192.168.75.21:80", host: "kac.corpus.com:88", referrer: "http://kac.corpus.com/index.php/extwidget/preview/partner_id/101/uiconf_id/23448134/entry_id/0_8snosjuo/embed/dynamic?&flashvars[akamaiHD]=%7B%22loadingPolicy%22%3A%22preInitialize%22%2C%22asyncInit%22%3A%22true%22%7D&flashvars[twoPhaseManifest]=true&flashvars[streamerType]=hdnetworkmanifest"
2015/10/08 18:44:54 [error] 44364#44364: *33 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 207.97.147.202, server: kac.corpus.com, request: "GET /hds/p/101/sp/10100/serveFlavor/entryId/0_8snosjuo/v/12/flavorId/0_,o0e4sjzi,t9lila38,uz8zj8o2,shkeltsk,5f3m40l2,/forceproxy/true/name/a.mp4.urlset/manifest.f4m?g=TMPFMHFHBYDG&hdcore=3.1.0&plugin=aasp-3.1.0.43.124 HTTP/1.1", host: "kac.corpus.com:88", referrer: "http://kac.corpus.com/index.php/extwidget/preview/partner_id/101/uiconf_id/23448134/entry_id/0_8snosjuo/embed/dynamic?&flashvars[akamaiHD]=%7B%22loadingPolicy%22%3A%22preInitialize%22%2C%22asyncInit%22%3A%22true%22%7D&flashvars[twoPhaseManifest]=true&flashvars[streamerType]=hdnetworkmanifest"

**Comment by erankor** [comment]
the parameter internal_ip_range in configurations/local.ini is most likely incorrect. the way it works is that the nginx server calls the serveFlavor API with a parameter of pathOnly=1. Since we do not want to expose the internal paths of the files outside the system, serveFlavor verifies that the request came from an internal address. you can set internal_ip_range to 0.0.0.0/0 in order to verify that is indeed the problem (but naturally it would be a good idea to put the real range in there)

**Comment by kaltura-hooks** [comment]
Hi @GeraldNathan,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by GeraldNathan** [comment]
Solve this issue, ( thanks to Jess ) Did the following  -

1.  updated to latest yum update "*kaltura*"
2.  nginx doesn't start after that -
Replace od_dash_include_segment_timeline off; with
vod_dash_manifest_format segmenttemplate;
3. temperorily changed local.ini to:
internal_ip_range = 0.0.0.0-255.255.255.255
3. restart apache, nginx - clear server cache and tested - Works !
