### ISSUE TITLE
Kaltura upload file error - File too large

### ISSUE THREAD

**Issue by aviya69** [kaltura/server#3705]
I installed Kaltura 11.5.0 and get an error when I'm trying to upload files bigger than 3MB.
The error that I got : 413 (Request Entity Too Large).

**Comment by kaltura-hooks** [comment]
Hi @aviya69,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by aviya69** [comment]
Hi,
I'm running self hosted single server Kaltura on CentOS 6.7 mysql version 5.1.73 
This is the rpm -qa "kaltura*" output:
kaltura-release-11.5.0-1.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-postinst-1.0.30-10.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-html5lib-v2.38.1-1.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-nginx-1.8.0-9.x86_64
kaltura-dwh-9.5.0-2.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-base-11.5.0-7.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-front-11.5.0-1.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-monit-5.13-1.x86_64
kaltura-sphinx-2.2.1-17.x86_64
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kmc-v5.39.11-6.noarch
kaltura-segmenter-1.0-2.x86_64
kaltura-batch-11.5.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kdp-v2.7.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-kupload-1.0.0-1.noarch
kaltura-html5-studio-v2.0.2-1.noarch
kaltura-librtmp-2.3-2.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-server-11.5.0-1.noarch

**Comment by jessp01** [comment]
Hello,

How are you trying to upload it? you cannot do so from KMC because that is limited to files up to 2G.
For bigger files, you need to either use bulk upload/drop folder, in which case the process is actually a download process, i.e: the server ingests a CSV/XML with URIs to the assets and downloads them and then does the normal mediainfo detection and transcoding process or, use the chunked upload API, for that you can see examples here:
https://developer.kaltura.org/recipes/upload
Choose the JS code, which uses http://kaltura.github.io/jQuery-File-Upload/
or an example in Java here:
https://github.com/kaltura/kaltura-chunked-upload-test

For additional questions around that, please post at forum.kaltura.org.
