### ISSUE TITLE
Java client API: Malformed UTF-8 decoding in response data in non-utf8 systems

### ISSUE THREAD

**Issue by canbulutb** [kaltura/server#3937]
Some UTF-8 special characters are not correctly decoded in response data, if the system default charset is not set to UTF-8.

### Example ###
`report->getTable(TOP_CONTENT_DROPOFF)` call returns video names with special characters in it which are not correctly decoded:
```
//response fragment from curl:
...Şubat...;

//response fragment from the API:
...??ubat...;
```

### Cause ###

**KalturaClientBase.java:**
```java
//String doReadRemoteInvocationResult(InputStream is) @ 307
    return new String(out.toByteArray());
```
This constructor decodes the byte array using the platform's default charset.
According to `String` javadoc:

> The behavior of this constructor when the given bytes are not valid in the default charset is unspecified. 

Furthermore,

**KalturaClientBase.java:**
```java
//String executeMethod(HttpClient client, PostMethod method) @ 355
    responseString = new String (responseBody.getBytes(), UTF8_CHARSET);
```

Again, according to the `String` javadoc, in the `getBytes()` method description:

> The behavior of this method when this string cannot be encoded in the default charset is unspecified.

### Solution ###
Providing `UTF-8` as the charset in `String` constructor should be enough to make sure the text is decoded properly:
```java
//String doReadRemoteInvocationResult(InputStream is) @ 307
    return new String(out.toByteArray(), UTF8_CHARSET);
```
Also, in the `executeMethod()` method, `responseString` should be correctly cast:
```java
//String executeMethod(HttpClient client, PostMethod method) @ 355
    responseString = new String (responseBody.getBytes(UTF8_CHARSET), UTF8_CHARSET);
```

**Comment by kaltura-hooks** [comment]
Hi @canbulutb,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @canbulutb,

I see you created a fix here:
https://github.com/canbulutb/server/commit/2a535aadeb0eadf2ec30d214dcdd03a6d62b8d3d

But I don't see a pull request to kaltura/server.. can you create one?

Thanks,

**Comment by canbulutb** [comment]
Hi Jess,
Thank you for quick response. I just signed the CLA and as soon as it gets processed, i will create one.
ThanksCan 

    On Tuesday, March 8, 2016 1:07 PM, Jess Portnoy <notifications@github.com> wrote:
 

 Hi @canbulutb,I see you created a fix here:
canbulutb@2a535aaBut I don't see a pull request to kaltura/server.. can you create one?Thanks,—
