### ISSUE TITLE
KalturaClient ClassCastException in Java client

### ISSUE THREAD

**Issue by jeffklassen** [kaltura/server#4088]
I'm trying to instantiate a client following the instructions here: http://www.kaltura.com/api_v3/testme/index.php# as follows:

```

//...

KalturaConfiguration config = new KalturaConfiguration();
config.setEndpoint("http://www.kaltura.com/");
KalturaClient client = new KalturaClient(config);
//...

```

And I get the following ClassCastException: 

```
Caused by: java.lang.ClassCastException: org.apache.log4j.Logger cannot be cast to com.kaltura.client.KalturaLoggerLog4j
    at com.kaltura.client.KalturaLoggerLog4j.get(KalturaLoggerLog4j.java:51)
    at com.kaltura.client.KalturaLogger.getLogger(KalturaLogger.java:37)
    at com.kaltura.client.KalturaLogger.getLogger(KalturaLogger.java:42)
    at com.kaltura.client.KalturaClientBase.<clinit>(KalturaClientBase.java:111)
```

**Comment by kaltura-hooks** [comment]
Hi @jeffklassen,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi, I suggest you look at the example here: https://github.com/kaltura/kaltura-chunked-upload-test
It also includes all the needed supported classes. It's possible you are simply using an incompatible version of log4j I suppose. I myself never came across such an error.

The precompiled classes were built with Java 7 so, if you use them as is, make sure you are using Java 7 as well, otherwise, recompile with your version.

**Comment by jeffklassen** [comment]
So, this is incompatible with log4j2, then?

**Comment by jeffklassen** [comment]
Additionally, I'm running the project from public static void main as follows:

``` 

public class KalturaVideoDownloader implements VideoDownloader {
	public static void main(String[] args) {
		System.out.println("Hello World");

		try {
			KalturaConfiguration config = new KalturaConfiguration();
			config.setEndpoint("http://www.kaltura.com/");
			KalturaClient client = new KalturaClient(config);
			String secret = "xx";
			String userId = "userid";
			KalturaSessionType type = null;
			int partnerId = 123;
			int expiry = 87089708;
			String privileges = null;
			Object result = client.getSessionService().start(secret, userId,
					type, partnerId, expiry, privileges);
		} catch (KalturaApiException e) {
			e.printStackTrace();
		}
	}

```

I'm not doing any manual configuration of log4j.

**Comment by jessp01** [comment]
Closing. No longer relevant.
