### ISSUE TITLE
Cannot find how to trigger export to external storage for existing videos.

### ISSUE THREAD

**Issue by kjrose** [kaltura/server#4095]
There does not seem to be an obvious way to trigger export for existing videos.

As well, I'm searching for a log console to make sure that I have it set up correctly, but I cannot seem to determine which log will have the details on the external storage procedures.

**Comment by kaltura-hooks** [comment]
Hi @kjrose,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kjrose** [comment]
Self-Hosted. RPM install on CentOS.

Kaltura-base-11.12.0-6.noarch
MySQL 5.1.73
Single, one server

No problematic request, I just cannot for the life of me figure out how to push videos that have already been converted to the external storage, nor can I find the logs for it to make sure it's working correctly.

**Comment by yossipapi** [comment]
FlavorAsset service has an export action that does exactly that.
You should provide the flavor's AssetId you want to export and the remoteStoargeId you want to export to.

**Comment by kjrose** [comment]
Thanks. That was precisely what I needed.
