### ISSUE TITLE
API change in MediaEntry categories and categoriesIds

### ISSUE THREAD

**Issue by moskiteau** [kaltura/server#4407]
We had a system in production using entry.categories and entry.categoriesIds to update categories associated with a mediaEntry.

This doesn't seem to work well anymore. We have cases where categories are just not added. Cases, where we update categories and some old deleted category gets added magically. I guess the point is that it is completely borked.

Even more weird, we have a staging account and we tested it before and after and it seems to work, so it is a problem hard to reproduce.

We contacted support and that's the answer we got:

> `Thank you for contacting Kaltura Customer Care,
> 1. Usually our Marketing department sent updates regarding major changes, in that case it is not a major change and this is the reason why no update email was sent.
> 2. As part of improving processes and products, sometimes we change core process, API calls for example, and it required to be always up to date with our last improvements.
> 
> 3.Generally all the information regarding APIs deprecated can be found in the provided documentation https://www.kaltura.com/api_v3/testmeDoc/
> 
> In addition, please note that the API call "baseEntry > get", which discussed in case number 00094105, is not deprecated, only the specific fields, "cateogries" and "categories_ids", under that call are deprecated and this is the reason why the word deprecated doesn’t appears near the "baseEntry > get" call.
> 
> Please let me know if any further assistance is required. 
> 
> Regards,  
> 
> Sapir Monza | Kaltura Customer Care | Kaltura Inc

`
I hope you guys realize how everything is wrong with this answer. 
1- Information about breaking change is not communicated??!!
2- Ever heard of API versionning?!
3- Nothing about this issue is in the documentation
4- huh? what is it that you are trying to say?

Thank you for helping me in this nonsense ;)

**Comment by kaltura-hooks** [comment]
Hi @moskiteau,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @moskiteau,
First off, sorry for the delay in response. Second, can you provide more info? what version are you using? Also, is this SaaS or CE?
Can you provide a code sample that currently malfunctions? I am unaware of changes made at the time of your initial posting that should cause breakage.

Thank you for reporting and hope we can get to the bottom of this together.

**Comment by jessp01** [comment]
Closing due to lack of response. @moskiteau - feel free to reopen and reply to my questions if there's still an issue.
