### ISSUE TITLE
Embed player doesn't play on IOS 9+

### ISSUE THREAD

**Issue by acegiak** [kaltura/server#4442]
In the Kaltura Management Console if I select an entry in the Content tab and then go to "Preview and Embed" regardless of which advanced options are selected, when the standalone page is loaded whether through the QR code or direct link, on IOS 9+ the video does not play when tapped on, instead it just shows the loading icon forever.

**Comment by kaltura-hooks** [comment]
Hi @acegiak,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by acegiak** [comment]
The issue only arises when trying to view the autoembed player on IOS9+

The kaltura is self-hosted running on a single server running kaltura-release-9.19.5-1. It is an RPM install.

The MySql version is Ver 14.14 Distrib 5.1.73.

I'll post logs from running the problematic request and screenshots tomorrow.

**Comment by acegiak** [comment]
No Errors appear when using the Log command provided above and triggering the problematic request. When I remove the grep section however there is obviously way too much information to be able to hunt through and find the issue.

See attached screenshots of problematic behaviour:

![image002](https://cloud.githubusercontent.com/assets/698430/16437723/5d2db6f6-3de8-11e6-9ab1-93806fa69038.png)
![image003](https://cloud.githubusercontent.com/assets/698430/16437724/5d325440-3de8-11e6-8188-9988235c9e34.jpg)

**Comment by doubleshot** [comment]
@acegiak You most likely need to update your html5 player for ios9 support. You didn't post your html5lib version, so can't be certain.

**Comment by jessp01** [comment]
@acegiak - we did not hear back from you but I imagine you upgraded and playback works correctly. The latest stable version is 2.48.1. If you haven't already, please upgrade.

Closing the issue but if, post upgrading, you're still having problems, feel free to reopen and provide a link to a sample embed code.
