### ISSUE TITLE
Installer fails, if NO_CA is set 

### ISSUE THREAD

**Issue by SteffenKockel** [kaltura/server#4633]
I realized, that the installer fails (on CentOS7) because of a faulty `sed` command in `kaltura-front-config.sh`. The following patch fixes this behavior.

```
--- kaltura-front-config.sh.org 2016-08-24 15:05:40.922895306 +0200
+++ kaltura-front-config.sh     2016-08-24 15:06:03.507193116 +0200
@@ -191,7 +191,7 @@
                sed -i "s^SSLCACertificateFile @SSL_CERTIFICATE_CHAIN_FILE@^SSLCACertificateFile $CHAIN_FILE^" $MAIN_APACHE_CONF
        else
                CA_FILE="NO_CA"
-               sed -i "s^SSLCACertificateFile @SSL_CERTIFICATE_CA_FILE@^#SSLCACertificateFile @SSL_CERTIFICATE_CA_FILE@^" $MAIN_APACHE_CONF
+                sed -i "s%^SSLCACertificateFile @SSL_CERTIFICATE_CHAIN_FILE@%#SSLCACertificateFile @SSL_CERTIFICATE_CHAIN_FILE%g" $MAIN_APACHE_CONF
        fi
        echo "IS_SSL=y" >> $RC_FILE 
        echo "CRT_FILE=$CRT_FILE" >> $RC_FILE```

**Comment by jessp01** [comment]
Hello,
Thank you for opening the issue, you are correct.
The source for kaltura-front-config.sh is here:
https://github.com/kaltura/platform-install-packages/blob/Lynx-12.0.0/RPM/scripts/postinst/kaltura-front-config.sh#L194

Since we like to properly credit contributors, it would be great if you can submit a pull request to the platform-install-packages repo.

Also, no need for '%' in the sed, it should basically be the same as it is now, only the token to replace is, like you said @SSL_CERTIFICATE_CHAIN_FILE@ and not @SSL_CERTIFICATE_CA_FILE@.

If you'd rather not submit the pull, I can fix it myself but like I said, I'd rather let git credit you instead of adding a commit comment to that affect:)

Do let me know.
Thanks again,

**Comment by kaltura-hooks** [comment]
Hi @SteffenKockel,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kaltura-hooks** [comment]
Hi @SteffenKockel,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by SteffenKockel** [comment]
I'll do a pull request for the patch

**Comment by SteffenKockel** [comment]
Ok, did a pull request and changed syntax according to jessp01's comment.

**Comment by jessp01** [comment]
Excellent. Please sign our CLA here https://agentcontribs.kaltura.org/ so I can merge it.

For future reference, the pull is here: https://github.com/kaltura/platform-install-packages/pull/562. Closing this issue.
Thanks again.

**Comment by SteffenKockel** [comment]
Sorry, can't fill in the form. Don't know my penis size... WTF?

**Comment by jessp01** [comment]
While I do appreciate the humour, there are legal needs that must be answered.
You can see examples of many highly dignified FOSS projects that require the same.
There is an explanation of this here:
https://github.com/kaltura/platform-install-packages/blob/IX-9.19.0/doc/Contributing-to-the-Kaltura-Platform.md#signing-the-contributor-license-agreement

But to provide some direct links:
The Apache Foundation - http://www.apache.org/licenses/icla.pdf
Fedora - https://fedoraproject.org/wiki/Legal:Fedora_Project_Contributor_Agreement
Ubuntu - http://www.ubuntu.com/legal/contributors/submit
MongoDB - https://www.mongodb.com/legal/contributor-agreement

You can see they all require similar information.
I can guarantee you none of that info will be shared with anyone apart from our legal team.
We will not insist on a valid telephone number but a legal physical address is needed.

**Comment by SteffenKockel** [comment]
Your arguments are valid, but I need to digest this. I'll sleep it over and have a look at my guts tomorrow.

**Comment by SteffenKockel** [comment]
OK, id did the form. Have fun!

**Comment by jessp01** [comment]
Thanks:) Pushed kaltura-postinst-1.0.31-21 package to 12.0.0. It will become the stable version on Sun.
