### ISSUE TITLE
Exported assets treated as absolute by DeliveryProfileX

### ISSUE THREAD

**Issue by jpluijmers** [kaltura/server#5007]
We have finished a migration exporting all VOD assets into external datastores which scale more easily than block based storage. 

Our process:
1. Each partner has a automatic remote storage profile, exporting to the external data store
2. Partner 0 has delivery profiles enforced by each partners remote storage profile. 
3. The remote storage has a nginx cache cluster in front of it equipped with the kaltura nginx-vod module in remote mode so no API calls. 

Since migrating the first clients to the external datastores, I have encountered the following issues:
1. media protocol did not get substituted on urls (http > https and vice versa)
2. in profiles of type DeliveryProfileVodPackerHls the /index.m3u8 did not get appended.

After some frantic searching with @jessp01 and @DBezemer I drilled down to the following line: 
https://github.com/kaltura/server/blob/Lynx-12.7.0/alpha/lib/model/DeliveryProfileVod.php#L269

This tells the delivery profile to return with the getExternalStorageUrl() and causing the issues above, since the calls to getAssetUrl is never made and mediaProtocol() substitution later down the line is never made, causing master.m3u8s like this:

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4227072,RESOLUTION=1920x1080
http:/CACHE_CLUSTER/hls/p/211/sp/211000/0_9qeksoad/2/0_g4xb007k.mp4
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=475136,RESOLUTION=480x272
http://CACHE_CLUSTER/hls/p/211/sp/211000/0_9qeksoad/2/0_1uz97bjb.mp4
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=679936,RESOLUTION=640x360
http://CACHE_CLUSTER/hls/p/211/sp/211000/0_9qeksoad/2/0_zlq6y26f.mp4
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=844800,RESOLUTION=640x360
http://CACHE_CLUSTER/hls/p/211/sp/211000/0_9qeksoad/2/0_g9a0nv2b.mp4
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1523712,RESOLUTION=1024x576
http://CACHE_CLUSTER/hls/p/211/sp/211000/0_9qeksoad/2/0_1k7dye8g.mp4
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2691072,RESOLUTION=1280x720
http://CACHE_CLUSTER/hls/p/211/sp/211000/0_9qeksoad/2/0_lg784swy.mp4

I hotfixed the following:
1. general getExternalStorageUrl to do mediaProtocol substitution
2. manifest specific (dash, hls) delivery profile types getExternalStorageUrl to append the suffixes.

I however doubt this is a great fix, what would be the correct way to permanently fix this?

**Comment by kaltura-hooks** [comment]
Hi @jpluijmers,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jpluijmers** [comment]
After talking it trough with @jessp01 we concluded that this issue is from 10.19 and up.

**Comment by jessp01** [comment]
Just for the benefit of anyone who visits this issue in the future, here is how it works in recent versions:

In the case of using an HLS [also called applehttp] delivery profile, this call:
https://github.com/kaltura/server/blob/Lynx-12.7.0/alpha/lib/model/DeliveryProfileVod.php#L205
Should lead to DeliveryProfileVodPackagerHls::doGetFileSyncUrl() and not to
https://github.com/kaltura/server/blob/Lynx-12.7.0/alpha/lib/model/DeliveryProfileVod.php#L226

Based on https://github.com/kaltura/server/blob/Lynx-12.8.0/alpha/lib/model/DeliveryProfilePeer.php#L71
https://github.com/kaltura/server/blob/Lynx-12.8.0/alpha/lib/enums/DeliveryProfileType.php#L44
61 being the value 'kaltura.delivery_profile.type' column contains in the HLS delivery profile record[s].
