### ISSUE TITLE
Wrong user credentials in KMC and Admin 

### ISSUE THREAD

**Issue by luc-espi** [kaltura/server#5112]
I just installed Kaltura Video Platform Community Edition and the user credentials are marked as wrong when I try to login with the same credentials I registered in install. I put my email into the Reset Password field but no email was sent.

I'm having trouble with logging in to https://kmc.kaltura.com/index.php/kmc aswell. It doesn't give login errors but it doesn't do anything.

I guess there is something wrong with my account: luc.espinach.bec@cellnextelecom.com

Thanks in advance.

**Comment by jessp01** [comment]
Hello,

You should not use the credentials set during the installation to log into KMC, you should instead log in to the Admin Console using them and then go to the 'Publishers' tab and create a new partner, then, you should get an email prompting you to reset the passwd but you can also directly login to KMC from Publishers->your partner row->actions->manage.

If you are having issues logging into Admin Console with the credentials you set during the installation process, then you should have a look at the log here: /opt/kaltura/log/kaltura_api_v3.log to understand why that is.

**Comment by kaltura-hooks** [comment]
Hi @luc-espi,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by luc-espi** [comment]
Hello,

Thanks for your prompt answer. 

By checking the file /opt/kaltura/log/kaltura_api_v3.log It can be seen that the kaltura user is not granted access to the kaltura database in mysql. When I try to grant access to the user it says that the database 'kaltura' doesn't exist:

[mysql:host=localhost;port=3306;dbname=kaltura;] user[kaltura] password[m2WvWCVPcbvxNK8] [wrapped: SQLSTATE[42000] [1044] Access denied for user 'kaltura'@'%' to database 'kaltura'] in /opt/kaltura/app/vendor/propel/Propel.php:649

Seems to be something wrong with my kaltura-db install. When I try to reinstall this package, asks for my mysql root password but always get the following error:
Warning: option 'port': value -N adjusted to 0
ERROR 2003 (HY000)

Thanks in advance

**Comment by jessp01** [comment]
Your Sphinx is down, as the message says.
Try:
\# service kaltura-sphinx restart
and then make sure it is actually up with:
\# service kaltura-sphinx status
and that you can connect to it with:
\# mysql -h127.0.0.1 -P9312

If something is wrong and it is still not up or you cannot connect to it, look at the logs under /opt/kaltura/log/sphinx/ to understand the reason.
If it is up and you can connect to it, you can re-run the config script.

**Comment by luc-espi** [comment]
That solved the problem.

Thanks sir!

**Comment by jessp01** [comment]
Welcome. For additional issues, please post at forum.kaltura.org instead. We'd rather use the GitHub issues section for bug reports exclusively rather than general troubleshooting.
