### ISSUE TITLE
KMC users created with API do no appear in the console

### ISSUE THREAD

**Issue by abrararshad** [kaltura/server#6506]
KMC users created with API client.user.add do not appear in the console. However, they can be retrieved using client.user.listacton. 

Using PHP

$kalturaUser = new \KalturaUser();
$kalturaUser->id = md5($id);
 $kalturaUser->screenName = $name;
$kalturaUser->email = $id;
$kalturaUser->firstName = $firstName;
$kalturaUser->lastName = $lastName;
$kalturaUser->description = 'Generated automatically';
$kalturaUser->roleIds = '21'; // 21 - Content Uploader
$kalturaUser->loginEnabled = false;
$kalturaUser->status = \KalturaUserStatus::BLOCKED;
$kalturaUser->isAccountOwner = false;

**Comment by kaltura-hooks** [comment]
Hi @abrararshad,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by yossipapi** [comment]
Hi @abrararshad 

when you say the user do not appear in the console, do you mean that you do not see them when navigating to the administration->Users page in the KMC?

If the answer to my question is yes:
KMC lists only users with isAdmin = 1 & loginEnabled = 1 and I don't see these values being set correctly in the code snippet you sent.
P.S I assume the KS used matches the account you tried to view users for.

**Comment by abrararshad** [comment]
Yes, it appears when I set isAdmin and loginEnabled to true. In my case I don't want users to login into KMC or be sort of any admin. Rather I use their KS generated locally in PHP to upload content. Even though they don't have login enabled and not admin, shouldn't they appear in KMC for moderation?

**Comment by yossipapi** [comment]
The KMC was designed to act as a management tool for admin users only thus it also filters in the administration tab only for such users.

The logic behind not showing none admin users in the KMC is that each partner may have different applications built over the Kaltura infrastructure and each one may have a different set of users. In such case application user management should better be handled within the application itself.

**Comment by abrararshad** [comment]
One more question. Is there any way to suppress the email notification sent upon creating a new Kaltura user?

**Comment by yossipapi** [comment]
An email is sent on a creation of a new partner when you are adding a new admin user to your account. Usually 2 emails are being sent:
1. To the email of the new user added. This is sent in case the user->add request did no contain the password information, if it did the email wont be sent.
2. To already other registered admin users with user management permissions.

The first one cannot be disabled.
The second one could be disabled by enabling the "FEATURE_DISABLE_NEW_USER_EMAIL" permission on your account. 

This could be done by sing the following API:
service = permission 
action = add
KalturaPermission.Name = FEATURE_DISABLE_NEW_USER_EMAIL
KalturaPermission. friendlyName = FEATURE_DISABLE_NEW_USER_EMAIL

**Comment by jessp01** [comment]
@abrararshad - if you want to completely disable email alerts about new partner and user creation, I suppose you could just drop these emails at your MTA [Mail Transport Agent] level.

The address from which these emails is sent is defined in /opt/kaltura/app/configurations/local.ini.
So, for instance, if you were to set the ```partner_registration_confirmation_email``` like so:
```
partner_registration_confirmation_email = dont_send@mykalturace.com
```
then reload Apache after the change and, in your MTA configuration [I like Postfix but Exim and all other common MTAs also support this option], define that all emails from dont_send@mykalturace.com should be dropped then no one will receive them. 

Of course, be sure to use a unique black listed address that none of your other scripts and applications use.

**Comment by jessp01** [comment]
@abrararshad - closing this issue but feel free to reopen should you have additional questions.
