### ISSUE TITLE
Kaltura CE video converting error

### ISSUE THREAD

**Issue by unbreakablearrow** [kaltura/server#6762]
Hi guys,

I have installed Kaltura community edition on Debian VPS few days back and everything seems working fine except when I upload video from Kaltura dashboard after successful uploading video, it automatically show video status "converting" and after some time the status shows "error" so it is failed to convert videos.

I have tried different transcending settings and also re-install Kaltura but issue remain the same :(

Requesting help to solve this issue please.

**Comment by jessp01** [comment]
Hi @unbreakablearrow,

First, make sure your batch daemon is running:
```
# /etc/init.d/kaltura-batch status
```
if it’s not running, try:
```
# /etc/init.d/kaltura-batch start
```
if it fails to start, take a look at the log file to understand why: /opt/kaltura/log/kaltura_batch.log

Assuming the batch daemon is running. see:
https://forum.kaltura.org/t/error-occurred-during-flavor-processing/5865/5

Once you have more info about the failure, we'll be able to help you further.
If the failure only occurs with certain source videos, please provide a link to such a video so I can further debug this locally.

**Comment by kaltura-hooks** [comment]
Hi @unbreakablearrow,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by unbreakablearrow** [comment]
Hi Jessp01,
Many thanks for quick action.

this is a result of first command which means its working:
Batch Manager running with PID 3559     [    OK    ]

I also visited your provided link which couldn't help :(

**Comment by jessp01** [comment]
Hi @unbreakablearrow,

Sorry but I don't understand what you mean by "it couldn't help":)
Please provide more info as to the jobs that ran on the video you've uploaded as I explained in the thread I referred you to. We need to know what ran, whether it failed or succeeded, what the error message was and so on. As I said, we also need to know whether this is specific to a certain video or happens with ALL videos you try to ingest.

**Comment by unbreakablearrow** [comment]
Hello kaltura-hooks,

Thank for help.

1. My issue is consist and not across platforms issue thing I believe! it happens on all conditions.
2. I Am using Kaltura CE self-hosted.
3. Using deb install.

When using RPM, paste the output for:
-bash: rpm: command not found
For deb based systems:
dpkg-query: no packages found matching "kaltura-*"

MySQL server version used: mysql  Ver 14.14 Distrib 5.5.58, for debian-linux-gnu (x86_64) using readline 6.3.

Its a single all in 1 server.

This command return nothing: # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"

**Comment by unbreakablearrow** [comment]
Hi jessp01,

I uploaded multiple Videos mostly extension MP4 and after uploading Kaltura show status in content tab that it is converting!!! but after some time depending on videos size the status change to "error" and it is happening after successful upload of any video! after successful upload it should convert video which its trying but rather success it shows simple status "error".

kindly check following screenshots,

After uploading: https://imgur.com/a/NRdbX
After some time when status change: https://imgur.com/a/4vPEW

Let me know if you other information or login details please...

Many Thanks for your help...

**Comment by jessp01** [comment]
Sorry but this doesn't help. As I wrote in the thread I referred you to:
Start by going to Admin Console->Batch Process Control. Input your entry ID and check what stages passed successfully and where it failed.
Next, look at the logs under /opt/kaltura/log/batch/ where each batch worker has its own dedicated log and error log. Check both for the following patterns “ERR:|PHP |Stack trace:|CRIT|[error]”, like so:
# grep -A 1 -B 1 --color “ERR:|PHP |Stack trace:|CRIT|[error]” /opt/kaltura/log/batch/*.log

Once you have that info, please post at forum.kaltura.org and I'll be able to help you further.

I'm closing the issue because this is clearly not a general bug in the server code and we'd rather use the repo's issues section for bug reports exclusively.

Thanks,
