### ISSUE TITLE
Preview & Embed video does not work 

### ISSUE THREAD

**Issue by msvittal** [kaltura/server#6787]
I am very new to Kaltura + NGINX etc. I just successfully installed Kaltura Single Box solution for Centos7.
I am able to upload my videos, but when I try to click on preview and embed link and play button I just see the spinner no video at all.

I guess that my transcoding or packaging is having issues. 

Failed to load resource: http://localhost:88/hls/p/101/sp/10100/serveFlavor/entryId/0_ttudnecg/v/2/ev/7/flavorId/0_4hldh7aq/name/a.mp4/index.m3u8 - the server responded with a status of 404 (Not Found)

Can some one help me here ?

**Comment by jessp01** [comment]
Hi @msvittal,

The Nginx host [running the kaltura-nginx package which includes the nginx-vod-module] needs to be accessible from all devices requesting playback. You can certainly put a load balancer in front of the Nginx nodes so that only it is accessible from the outside, SSL offloading to the nodes.

For more info, see: https://forum.kaltura.org/t/vod-packager-and-primary-media-server-host/7922/2
Which also includes several links to related documentation, 

Should you have additional questions, please post them on the forum. We'd rather use the repo's issues section for bug reports only, rather than for general questions.

Thanks,
